name: Run tests with dispatch

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository which triggered workflow'
        required: true
        default: 'unknownRepository'
      run_id:
        description: 'check run id'
        required: true
        default: 'unknownId'
      branch:
        description: 'Branch in repository'
        required: true
        default: 'unknownBranch'
      sha:
        description: 'SHA'
        required: true
        default: 'sha'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: showing inputs
        id: test
        run: |
          echo Repo is ${{ github.event.inputs.repo }}
          echo run_id is ${{ github.event.inputs.run_id }}
          echo branch is ${{ github.event.inputs.branch }}

      - name: pending for ${{ github.event.inputs.branch }} at ${{ github.event.inputs.repo }} repo
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.ROBOT_TOKEN }}" \
            https://api.github.com/repos/${{ github.event.inputs.repo }}/statuses/${{ github.event.inputs.sha }} \
            -d '{
              "state": "pending",
              "context": "UI tests",
              "description":"Test execution has been started",
              "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

      - name: pending for ${{ github.event.inputs.branch }} at ${{ github.event.inputs.repo }} repo
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.ROBOT_TOKEN }}" \
            https://api.github.com/repos/${{ github.event.inputs.repo }}/statuses/${{ github.event.inputs.sha }} \
            -d '{
              "state": "pending",
              "context": "API tests",
              "description":"API Test execution has been started",
              "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

      - name: Sleep
        run: sleep 1m

      - name: Success for API tests
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.ROBOT_TOKEN }}" \
            https://api.github.com/repos/${{ github.event.inputs.repo }}/statuses/${{ github.event.inputs.sha }} \
            -d '{
              "state": "success",
              "context": "API tests",
              "description": "API Test execution was succeded",
              "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'


      - name: Success for tests
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.ROBOT_TOKEN }}" \
            https://api.github.com/repos/${{ github.event.inputs.repo }}/statuses/${{ github.event.inputs.sha }} \
            -d '{
              "state": "success",
              "context": "UI tests",
              "description": "Test execution was succeded",
              "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
