name: example-start-and-yarn-workspaces
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          working-directory: packages/platform-ui
          build: yarn run build
          start: yarn start
          wait-on: 'http://localhost:3000'
      - name: Cypress tests
        uses: ./
        build: yarn cy:run
